### ISSUE TITLE
AM PM

### ISSUE THREAD

**Issue by ahmed-tasaly** [alfajrimutawadhi/salat#2]
### Assalam Alaykom
**Can you add (12-hours style ---->>> am and pm ) ?**

Thanks in advance

**Comment by alfajrimutawadhi** [comment]
@ahmed-tasaly Sure, thanks for your improvisation

**Comment by alfajrimutawadhi** [comment]
@ahmed-tasaly You can reinstall the latest version to be able to use the new features. Thanks 😁
